/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as R403RouteImport } from './../routes/403'
import { Route as R404RouteImport } from './../routes/404'
import { Route as AdminRouteRouteImport } from './../routes/admin/route'
import { Route as AdminIndexRouteImport } from './../routes/admin/index'
import { Route as AdminWorldsRouteImport } from './../routes/admin/worlds'
import { Route as AuthSignInRouteImport } from './../routes/auth/sign-in'
import { Route as WorldsIndexRouteImport } from './../routes/worlds/index'
import { Route as WorldsSlugRouteImport } from './../routes/worlds/$slug'
import { Route as AdminWorldsSlugRouteImport } from './../routes/admin/worlds.$slug'
import { Route as AdminWorldsNewRouteImport } from './../routes/admin/worlds.new'
import { Route as WorldsSlugAboutRouteImport } from './../routes/worlds/$slug_.about'
import { Route as WorldsSlugResidentsRouteImport } from './../routes/worlds/$slug_.residents'
import { Route as WorldsSlugPostsPostIdRouteImport } from './../routes/worlds/$slug_.posts.$postId'
import { Route as WorldsSlugResidentsCharacterIdRouteImport } from './../routes/worlds/$slug_.residents_.$characterId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminWorldsRoute = AdminWorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsIndexRoute = WorldsIndexRouteImport.update({
  id: '/worlds/',
  path: '/worlds/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsSlugRoute = WorldsSlugRouteImport.update({
  id: '/worlds/$slug',
  path: '/worlds/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorldsSlugRoute = AdminWorldsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminWorldsRoute,
} as any)
const AdminWorldsNewRoute = AdminWorldsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminWorldsRoute,
} as any)
const WorldsSlugAboutRoute = WorldsSlugAboutRouteImport.update({
  id: '/worlds/$slug_/about',
  path: '/worlds/$slug/about',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsSlugResidentsRoute = WorldsSlugResidentsRouteImport.update({
  id: '/worlds/$slug_/residents',
  path: '/worlds/$slug/residents',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsSlugPostsPostIdRoute = WorldsSlugPostsPostIdRouteImport.update({
  id: '/worlds/$slug_/posts/$postId',
  path: '/worlds/$slug/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsSlugResidentsCharacterIdRoute =
  WorldsSlugResidentsCharacterIdRouteImport.update({
    id: '/worlds/$slug_/residents_/$characterId',
    path: '/worlds/$slug/residents/$characterId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/admin/worlds': typeof AdminWorldsRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/worlds/$slug': typeof WorldsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/worlds/': typeof WorldsIndexRoute
  '/admin/worlds/$slug': typeof AdminWorldsSlugRoute
  '/admin/worlds/new': typeof AdminWorldsNewRoute
  '/worlds/$slug/about': typeof WorldsSlugAboutRoute
  '/worlds/$slug/residents': typeof WorldsSlugResidentsRoute
  '/worlds/$slug/posts/$postId': typeof WorldsSlugPostsPostIdRoute
  '/worlds/$slug/residents/$characterId': typeof WorldsSlugResidentsCharacterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/admin/worlds': typeof AdminWorldsRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/worlds/$slug': typeof WorldsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/worlds': typeof WorldsIndexRoute
  '/admin/worlds/$slug': typeof AdminWorldsSlugRoute
  '/admin/worlds/new': typeof AdminWorldsNewRoute
  '/worlds/$slug/about': typeof WorldsSlugAboutRoute
  '/worlds/$slug/residents': typeof WorldsSlugResidentsRoute
  '/worlds/$slug/posts/$postId': typeof WorldsSlugPostsPostIdRoute
  '/worlds/$slug/residents/$characterId': typeof WorldsSlugResidentsCharacterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/admin/worlds': typeof AdminWorldsRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/worlds/$slug': typeof WorldsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/worlds/': typeof WorldsIndexRoute
  '/admin/worlds/$slug': typeof AdminWorldsSlugRoute
  '/admin/worlds/new': typeof AdminWorldsNewRoute
  '/worlds/$slug_/about': typeof WorldsSlugAboutRoute
  '/worlds/$slug_/residents': typeof WorldsSlugResidentsRoute
  '/worlds/$slug_/posts/$postId': typeof WorldsSlugPostsPostIdRoute
  '/worlds/$slug_/residents_/$characterId': typeof WorldsSlugResidentsCharacterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/403'
    | '/404'
    | '/admin/worlds'
    | '/auth/sign-in'
    | '/worlds/$slug'
    | '/admin/'
    | '/worlds/'
    | '/admin/worlds/$slug'
    | '/admin/worlds/new'
    | '/worlds/$slug/about'
    | '/worlds/$slug/residents'
    | '/worlds/$slug/posts/$postId'
    | '/worlds/$slug/residents/$characterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/404'
    | '/admin/worlds'
    | '/auth/sign-in'
    | '/worlds/$slug'
    | '/admin'
    | '/worlds'
    | '/admin/worlds/$slug'
    | '/admin/worlds/new'
    | '/worlds/$slug/about'
    | '/worlds/$slug/residents'
    | '/worlds/$slug/posts/$postId'
    | '/worlds/$slug/residents/$characterId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/403'
    | '/404'
    | '/admin/worlds'
    | '/auth/sign-in'
    | '/worlds/$slug'
    | '/admin/'
    | '/worlds/'
    | '/admin/worlds/$slug'
    | '/admin/worlds/new'
    | '/worlds/$slug_/about'
    | '/worlds/$slug_/residents'
    | '/worlds/$slug_/posts/$postId'
    | '/worlds/$slug_/residents_/$characterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  R403Route: typeof R403Route
  R404Route: typeof R404Route
  AuthSignInRoute: typeof AuthSignInRoute
  WorldsSlugRoute: typeof WorldsSlugRoute
  WorldsIndexRoute: typeof WorldsIndexRoute
  WorldsSlugAboutRoute: typeof WorldsSlugAboutRoute
  WorldsSlugResidentsRoute: typeof WorldsSlugResidentsRoute
  WorldsSlugPostsPostIdRoute: typeof WorldsSlugPostsPostIdRoute
  WorldsSlugResidentsCharacterIdRoute: typeof WorldsSlugResidentsCharacterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/worlds': {
      id: '/admin/worlds'
      path: '/worlds'
      fullPath: '/admin/worlds'
      preLoaderRoute: typeof AdminWorldsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/': {
      id: '/worlds/'
      path: '/worlds'
      fullPath: '/worlds/'
      preLoaderRoute: typeof WorldsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/$slug': {
      id: '/worlds/$slug'
      path: '/worlds/$slug'
      fullPath: '/worlds/$slug'
      preLoaderRoute: typeof WorldsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/worlds/$slug': {
      id: '/admin/worlds/$slug'
      path: '/$slug'
      fullPath: '/admin/worlds/$slug'
      preLoaderRoute: typeof AdminWorldsSlugRouteImport
      parentRoute: typeof AdminWorldsRoute
    }
    '/admin/worlds/new': {
      id: '/admin/worlds/new'
      path: '/new'
      fullPath: '/admin/worlds/new'
      preLoaderRoute: typeof AdminWorldsNewRouteImport
      parentRoute: typeof AdminWorldsRoute
    }
    '/worlds/$slug_/about': {
      id: '/worlds/$slug_/about'
      path: '/worlds/$slug/about'
      fullPath: '/worlds/$slug/about'
      preLoaderRoute: typeof WorldsSlugAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/$slug_/residents': {
      id: '/worlds/$slug_/residents'
      path: '/worlds/$slug/residents'
      fullPath: '/worlds/$slug/residents'
      preLoaderRoute: typeof WorldsSlugResidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/$slug_/posts/$postId': {
      id: '/worlds/$slug_/posts/$postId'
      path: '/worlds/$slug/posts/$postId'
      fullPath: '/worlds/$slug/posts/$postId'
      preLoaderRoute: typeof WorldsSlugPostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/$slug_/residents_/$characterId': {
      id: '/worlds/$slug_/residents_/$characterId'
      path: '/worlds/$slug/residents/$characterId'
      fullPath: '/worlds/$slug/residents/$characterId'
      preLoaderRoute: typeof WorldsSlugResidentsCharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminWorldsRouteChildren {
  AdminWorldsSlugRoute: typeof AdminWorldsSlugRoute
  AdminWorldsNewRoute: typeof AdminWorldsNewRoute
}

const AdminWorldsRouteChildren: AdminWorldsRouteChildren = {
  AdminWorldsSlugRoute: AdminWorldsSlugRoute,
  AdminWorldsNewRoute: AdminWorldsNewRoute,
}

const AdminWorldsRouteWithChildren = AdminWorldsRoute._addFileChildren(
  AdminWorldsRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminWorldsRoute: typeof AdminWorldsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminWorldsRoute: AdminWorldsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  R403Route: R403Route,
  R404Route: R404Route,
  AuthSignInRoute: AuthSignInRoute,
  WorldsSlugRoute: WorldsSlugRoute,
  WorldsIndexRoute: WorldsIndexRoute,
  WorldsSlugAboutRoute: WorldsSlugAboutRoute,
  WorldsSlugResidentsRoute: WorldsSlugResidentsRoute,
  WorldsSlugPostsPostIdRoute: WorldsSlugPostsPostIdRoute,
  WorldsSlugResidentsCharacterIdRoute: WorldsSlugResidentsCharacterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
