// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma', // Recursively checks the /prisma directory for the schema models and merges them
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed-world.ts',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
